language: node_js
cache:
  directories:
    - ~/.npm
git:
  depth: 3
deploy:
  provider: pages
  edge: true
  local-dir: src/
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  commit_message: "Deploy Release"
  on:
    branch: master